included:
  - contrail

identifier_name:
  min_length:
    warning: 1
    error: 1

type_name:
  min_length:
    warning: 1
    error: 1

line_length:
  warning: 300
  error: 500

opt_in_rules:
  - closure_spacing

disabled_rules:
  - force_cast
