name: contrail

options:
  bundleIdPrefix: dev.tokizuoh
  developmentLanguage: ja
  deploymentTarget:
    iOS: 15.4
  xcodeVersion: "13.3"

settings:
  base:
    DEVELOPMENT_TEAM: 2YRXH6ZZZY
    MARKETING_VERSION: 1.0.0
    CURRENT_PROJECT_VERSION: 1
    CODE_SIGN_STYLE: Manual
    INFOPLIST_KEY_UILaunchScreen_Generation: YES

targets:
  contrail:
    type: application
    platform: iOS
    sources:
      - contrail
    settings:
      base:
        ENABLE_PREVIEWS: YES
        DEVELOPMENT_ASSET_PATHS: "\"contrail/Preview Content\""
        PROVISIONING_PROFILE_SPECIFIER: contrailProvisioning
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        CODE_SIGN_ENTITLEMENTS: contrail/contrail.entitlements
        CODE_SIGN_IDENTITY: iPhone Developer
        CODE_SIGN_STYLE: Manual
        CURRENT_PROJECT_VERSION: 1
        DEVELOPMENT_ASSET_PATHS: "\"contrail/Preview Content\""
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_FILE: contrail/Info.plist
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        LD_RUNPATH_SEARCH_PATHS: '$(inherited) @executable_path/Frameworks'
        SWIFT_EMIT_LOC_STRINGS: YES
        SWIFT_VERSION: 5.0
    info:
      path: contrail/Info.plist
      properties:
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        NSHealthShareUsageDescription: Get a bike workout.
        LSRequiresIPhoneOS: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        UIRequiresFullScreen: YES
        UIApplicationSceneManifest: 
          UIApplicationSupportsMultipleScenes: YES
        UISupportedInterfaceOrientations~iphone:
          [UIInterfaceOrientationPortrait, UIInterfaceOrientationLandscapeLeft, UIInterfaceOrientationLandscapeRight]
        UISupportedInterfaceOrientations~ipad:
          [UIInterfaceOrientationPortrait, UIInterfaceOrientationPortraitUpsideDown, UIInterfaceOrientationLandscapeLeft, UIInterfaceOrientationLandscapeRight]
    preBuildScripts:
      - path: scripts/mockolo.sh
        name: Mockolo
      - path: scripts/swiftlint.sh
        name: SwiftLint
  contrailTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - contrailTests
    dependencies:
      - target: contrail