name: CI

on:
  pull_request:
    types:
      - closed
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - name: Select Xcode version
      run: sudo xcode-select -s '/Applications/Xcode_13.3.app/Contents/Developer'
    - name: Show Xcode version
      run: xcodebuild -version
    - name: Install Mint
      run: brew install mint
    - name: Mint Bootstrap
      run: mint bootstrap
    - name: Build
      run: xcodebuild -sdk iphonesimulator -configuration Debug build 