name: CI

on:
  pull_request:
    types:
      - closed

jobs:
  build:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v1
    - name: Select Xcode version
      run: sudo xcode-select -s '/Applications/Xcode_13.3.app/Contents/Developer'
    - name: Show Xcode version
      run: xcodebuild -version
    - name: Build
      run: xcodebuild -sdk iphonesimulator -configuration Debug build 